name: Deploy to Google Cloud Instance

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Google Compute Engine Instance
      env:
        INSTANCE_NAME: "poc-php"  # The name of your instance in Google Cloud
        INSTANCE_IP: "34.29.54.77"  # The public IP address of your Google Cloud instance
        SSH_USER: "kiranpranay12"  # The SSH user for your Google Cloud instance
        SSH_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}  # Your private SSH key stored in GitHub Secrets
        DEPLOY_SCRIPT: "Script.sh"  # The script to run on the instance
      run: |
        # Write SSH key to a file
        echo "$SSH_KEY" > private_key
        chmod 600 private_key

        # Start ssh-agent and add the private key with the passphrase
        eval "$(ssh-agent -s)"
        echo "bannu" | ssh-add private_key

        # Add the instance IP to known_hosts to prevent interactive prompts
        mkdir -p ~/.ssh
        ssh-keyscan -H "$INSTANCE_IP" >> ~/.ssh/known_hosts

        # Ensure the deployment script exists
        if [ ! -f "$DEPLOY_SCRIPT" ]; then
          echo "Deployment script $DEPLOY_SCRIPT not found!"
          exit 1
        fi

        # Copy the script to the instance
        scp -o StrictHostKeyChecking=no -i private_key "$DEPLOY_SCRIPT" "$SSH_USER@$INSTANCE_IP:~/"

        # Connect to the instance and execute the script
        ssh -o StrictHostKeyChecking=no -i private_key "$SSH_USER@$INSTANCE_IP" "bash ~/Script.sh"

    - name: Cleanup
      if: always()
      run: |
        # Remove the private key after use to keep it secure
        rm -f private_key
