name: Deploy to Google Cloud Instance

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Compute Engine Instance
      run: |
        # Define variables
        INSTANCE_NAME="poc-php"
        ZONE="us-central1-b"  # Replace with your instance's zone
        SSH_USER="kiranpranay12"  # Replace with the user for the instance
        SSH_KEY="-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBi8FtCzO
8d47mHdae70Xc0AAAAEAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQDKgLYScAhc
vjQJgIg34zxwy1CR3gC3V2QKGOE36DI0nhmglbE6or1oB8yVWZ4Gaq1uvtYFtyQH1qNExz
E5yycK+E3CFzNwFTNz46SuSucqb+mUcMmojKF+Gwu3rGVXmyXPaY2gU9IsdrB3XiFOHTwt
0WTCWrm+Ieakg0dNsbWJdcgxhA6f9GeBIJaepRlOd1J3rvW/o8jdba3RmOmLPRlIH+fQAc
emV1pOtQz8U8tkMeG5qXZ2oL8SEJDayznQ1Do2014p/T3CR9OKQSgRgZS5Iu/WdhGOPRRf
nC510/1qsaMQDZdFJ12OVKgXh7tu1Fy+VN7AAzoIqUXERnpK/gzy0LjBqTiIA/csX/s5K9
vTwFWKkoM8vEHqHhM/YyEL8ooNoaxduS71xvUjgpH5xE64lR9A9W8xW0IkpFH64B/n9lH2
wg4pQtfHS1gbL3teaHM3NiiCRnM+eOkFoP9b1cO63lkmeRJDFjExXgsVQpjFLenxSrb4lp
ZljbAL09alLmnWXN+f5y6lERRxTKSMffH0oT+WcFke9MLh7MlSEpbE8/cEoSEXcXsW8UMK
K67FmWpksihQZRuG6Q29OCUC1mYy3LgCN4IXMAEYFEvVeysjejZ5jx6urlku8RgOl/kHag
pztg9NzZumHSKGTsWFIZWVE8DtglA5TZg5uhdk+kNuywAAB1B/OeXp4+lsIGx+0kvzG2bW
l+ZYsi2FFb2m8GJjWVs2Mswmk149GUyTnvlnuA5rbJ6pVNX7fnMXRA2MeIKRJZUqoHNSf4
xaLg/Vc4rlR4pvy1qU8CimhlICacEk7LsTKJUbSwLEqiZi5eE5MrK00BS0sMiavmPop8OF
OktiXherCHAib+8D7moZg7FH/z9waURZhaNNi2VDNdG4l1WaiBhLlWnu2AiUEtSQWpiTL8
MW2SYIuvZSQNXHlmmQ+nRjde7MpJ565/pRkzvsJaTrQLeqRz9GK5O3ppYKGPyLsqpr7Lce
MvN8m9D8+yUjMrargkccgh+ZEE5ElTK4w6Q+7Oy+HHkroqo/bTWUvgoaDaLhh3ERq4zKuZ
Th3hKxvmIfKI7F5r+DItm3aCPoAF2WhrgFE+SWostrRUN0gyZccksquFN+sMaeNLsqDDL6
vmkX7d0wzV0pcsKx2xmJqk9RLkH2qcMKDh4EndV3caUBiAls8MUBbHP9xFr7V7PH1UB/SL
6qV3Jdo31nNTdqs0X9z/LJJTfvDzIZIGo/IybfhCVlBZQHIiTRMcXArY/dp2NcWcVT8aoy
/YsTJZfEa7ShDzfs2rVWn01Yf7ZnPTYWcrkO3TboxQtNtkUuGShcTJCvnI/weOfd1Olxia
7VL3bfyuw6we4t5WzRg9WAeyxtjGCEs8IVE3R/wVaGh3Wyz4GwvRrZEl9pNgjC+nLQpdvf
r1IJ1aZ5TMb0d4cOko46o8POX4Z/2yMNsRpGoQZxFeUxpGWaCYSN6yRnGfYDJ0q2yuJkMN
Xh70aLrGCYC8lk9R2aamvXXuJe4WHH7ARxx8cOXp9nsE4ylAbOhKrVoOAOQVpkHmEGJPxM
6joQr0DDTIAbzLy4fOREVYZVkevu5hwsQQbVHiTdHJDmetUdYLhScJvFqgrS9i132T0Vc7
AtVRT2yevUjloSaNzYN3CgZPrtha2XpOfab20q5KsglSKj8ZN1QklOIK4WooMnAbmO2zbJ
D6e4KYQz5df8qHxhrT5K320D6s939QN2E3cZt1nNucfgX86mM21IGMhZg21+zuDHtfV//k
bz69S/5Jjc3s8PwLYEfFQB9arGcNqW7Q49YKXLT7v6GXpx4R5fKdQdNGDfRFBZEGcA3Dw6
dX13vBewIa011bwmtsQ/4Hi4MQavVHxUSBgL1S25haU25X3rRKHcerTAiw0UxjU/9Aq8Me
qrKrUaaDjoNh7jtMC8jOfZgPOcX+rYL8g/z2OR4YMAyPHH2C8cCXmI2cTBwH5gQsNDQ05b
bi6eZlOWh/wWsWmtHWhYs8DerBR1eoS1EewiPsUOf70zQ50D0n2kCEjUFeP7HSrHGcWu8O
RBFkmbmzuPHdNi7NJTASkn6Ilsal70VXojqc1YCZG1tUzYU0B6isKoGjKxFahG3bIw6PZu
LEAfAON4XNHVc9IEQDam0aguTAfrWaYVOzvclZv1BbI0cg/KODpmezXMke4qmjE7FUIsDP
AFrtySXv/RfUG/Qcg5QSLEZw0RIh3nwChI8yGZRhG3Zleg1+ps3CbHnK7iwmqII1M4bCAY
mlBplPodY0qyzDKhlgw2a6Djcjsy8mTz9qsS3/VOigC6aERpnmQxPsBsPtI0w5w9bR77oy
1rYg998gI7NSY1TYgf8PKX8DEDMaOdWgTEz1zjZWXcICk7bVaRF5qDecf8289IUVR0VsPj
DV+GPf044CXJxraVhlzlKtlELoQZxWi8zX82fXxpnqIqnmtEUXzTxWVciDCQVhd5HQ1sAJ
29qT2XDcBuYAKZaGFYaheJ+6Qt1jfWa8JTNipGYu0AhH+j5W0h6L2Qtla2xLAjH/iSrJD4
+Egfj4FgDT5aYm8Y+vCLHipMDO/Ql6JIFY1tC2zl5T689dW8vQM+07BlBXmFfA8nVGGdwH
G692dA7NEbRM3Wsvalki5gCWX9+juFQqKUVQyA87G8J48NCXFvChPGwPh+jJvZiDxk1ZUU
Wx9jPD4IjV7AlXbESVZfEB4rxpK1bUVlykWOMqzBUzlA2sGKzPDXPO6m6A0nKiBPBC+tx4
Vr8bA5l5nSZi7f+ZD76k/owzuhFw4146kI2c+f63dpjc1TTRhYSMfP9Wos6UantjRiuV3Z
1f2YPCU8qicQE9JBiB7EtFlyeGXoKqpW5MGj03FT5TGoMd4n1j5b3r2+E/DiUte5EIO+Bm
E67qdv8Zgue3eW3aQB6gMY+tUx0L1xBJGkKwiL5ESKEZvQOJukNr0Cjll6iWFbGbxlAHQo
c4a5f5fV/YOYKOluxyep15aZ65ps6GHL3Z0zZMI8NQlzYY9fm3ObjiLOEMYgL6OzHGbshQ
iadCU4I+tc/tHRqVVtwEeM+OeZ7MV5InxZBdtpENtIVuqFBuNl4GLUDjnPb0C/3c9FANtf
JAn6ZFVJZV+/5+2f9yONMWaxKmlukkqn252G9MTAxNx5vS8h8CEfIxUAs17ai/KXwt6Dxp
vFwKjC87RVLiZ86Gl/1KA2MEc=
-----END OPENSSH PRIVATE KEY-----"  # Add private SSH key to secrets
        DEPLOY_SCRIPT="Script.sh"  # Script to run on the instance

        # Write SSH key to a file
        echo "$SSH_KEY" > private_key
        chmod 600 private_key
        

        # Generate public key
        ssh-keygen -y -f private_key > private_key.pub

        mkdir -p ~/.ssh

        # Add the instance to known_hosts to prevent host key verification issues
        ssh-keyscan -H 34.29.54.77 >> ~/.ssh/known_hosts

        # Add the instance to known_hosts to prevent host key verification issues
        ssh-keyscan -H 34.29.54.77 >> ~/.ssh/known_hosts

        # Connect to the instance and execute the script
        scp -i private_key $DEPLOY_SCRIPT "$SSH_USER@34.29.54.77:~/"
        ssh -i private_key "$SSH_USER@34.29.54.77" "bash ~/Script.sh"

    
